get_win_error: drop trailing <CR><LF>
Some occurences of this call (net_udp.cpp, dlfunc.c) don't expect the
string to be terminated so it is perhaps better to drop it at the
source.