configure.ac: incl -latomic on 32b aarch64 builds
\-latomic is needed to prevent errors:
```
undefined reference to `__atomic_load_8'
````
even if target_cpu is aarch64 but building on 32-bit Raspberry Pi OS
(which is still default).